import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import homeStyles from "../styles/modules/home.module.scss";
import footerStyles from "../styles/modules/footer.module.scss";

const Layout: NextPage = ({ children }) => {
  return (
    <div className={homeStyles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>{children}</main>

      <footer className={footerStyles.footer}>
        <a href="https://niteco.com/" target="_blank" rel="noopener noreferrer">
          Powered by{" "}
          <span className={footerStyles.logo}>
            <Image src="/images/niteco.svg" alt="Niteco Logo" width={80} height={20} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;
