import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/modules/home.module.scss";
import Header from "../components/header";
import Link from "next/link";
import Layout from "../components/layout";
import ProductSummary from "./products/product-summary";
const categories = require("../data/categories.json");

interface HomePageProps {
  categories: any;
}

export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      categories,
    },
  };
};

const Home: NextPage<HomePageProps> = ({ categories }) => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className={styles.bannerContainer}>
        <Image src="/images/washerdryer-banner.jpg" alt="Elextrolux banner" layout="fill" objectFit="contain" />
        <div className={styles.bannerInner}>
          <div className={styles.bannerContent}>
            <div className={styles.bannerTitle}>Promotion</div>
            <Link href="/">
              <a className={styles.bannerLink}>See more</a>
            </Link>
          </div>
        </div>
      </div>
      <div className={styles.mainContent}>
        {categories &&
          categories.map((item: any) => (
            <div key={item.id} className={styles.categoryItem}>
              <Link href="/">
                <a className={styles.categoryImage}>
                  <Image src={`/images/${item.image}`} alt={item.name} layout="fill" objectFit="contain" />
                </a>
              </Link>
              <div className={styles.categoryContent}>
                <p>{item.name}</p>
                <Link href="/">
                  <a className={styles.categoryCtaButton}>See more</a>
                </Link>
              </div>
            </div>
          ))}
      </div>
      <div className={styles.introduceSection}>
        <h2>Why Electrolux?</h2>
        <div className={styles.introduceContent}>
          <div className={styles.introduceItem}>
            <div className={styles.introduceIcon}>
              <Image src={`/images/icons/free-returns-icon.svg`} alt="Elextrolux icon" layout="fill" objectFit="contain" />
            </div>
            <p>90 days trial</p>
          </div>
          <div className={styles.introduceItem}>
            <div className={styles.introduceIcon}>
              <Image src={`/images/icons/free-shipping-icon.svg`} alt="Elextrolux icon" layout="fill" objectFit="contain" />
            </div>
            <p>Free ship</p>
          </div>
          <div className={styles.introduceItem}>
            <div className={styles.introduceIcon}>
              <Image src={`/images/icons/free-installation-icon.svg`} alt="Elextrolux icon" layout="fill" objectFit="contain" />
            </div>
            <p>Free installation</p>
          </div>
          <div className={styles.introduceItem}>
            <div className={styles.introduceIcon}>
              <Image src={`/images/icons/free-installment-icon.svg`} alt="Elextrolux icon" layout="fill" objectFit="contain" />
            </div>
            <p>Free installment</p>
          </div>
          <div className={styles.introduceItem}>
            <div className={styles.introduceIcon}>
              <Image src={`/images/icons/warranty-icon.svg`} alt="Elextrolux banner" layout="fill" objectFit="contain" />
            </div>
            <p>2 years warranty</p>
          </div>
        </div>
      </div>
      <ProductSummary />
    </Layout>
  );
};

export default Home;
